---
case: 0

log:
  state: 0
  file: fenite.log

protocol:
  type: 0
  request:
    timeout: 0
    limit: 1
  webhook:
    port: 8080

trigger: "/"

token: 6031533206:AAGBZMegAWCGoylgPiDRsX10G8IfGu467hM 

ownchat: 0

codename: bot_name
